### ISSUE TITLE
why do u use R2DBC 

### ISSUE THREAD

**Issue by fizz12344321** [jesperancinha/concert-demos-root#246]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by jesperancinha** [comment]
Hi @fizz12344321 , this project is focused on reactive programming and it's almost 3 years old. At the time, we were looking at ways to implement our FINTECH application using reactive paradigms in order to provide more resources and release the application to keep processing more requests. The combination of  Spring WebFlux and R2DBC was something we looked at. [R2DBC](https://r2dbc.io/) is fully reactive and non-blocking. There are many ways to create reactive repos and nowadays that might change even further with the inception of Java Virtual Threads or Kotlin Coroutines. My article for this repo, describes my findings at the time and the perception I had on what this architecture could do for us. I does need a revision though, which will happen soon.  So in other words this project attempts to show a functional example of a fully reactive MVC application.

**Comment by jesperancinha** [comment]
It's not about being faster. Not directly at least. It's about releasing unnecessary resources as soon as possible in order to maximise staying responsive. It eventually leads to systems being faster as a whole, but the idea is simply and as an example to instead of only supporting 100 requests at once, you can then support 10000 requests at once (figures are just to emphasise an example of course).
